### ISSUE TITLE
Alignment 

### ISSUE THREAD

**Issue by CyrilShch** [keleog/PidginUNMT#3]
Thank you for your work!

Could you please specify how you got:

params.src_emb = 'cbow_15.txt'
params.tgt_emb = 'glove.6B.300d.txt'

Specifically, these files?
params.dico_train = 'final_dict.txt'
params.dico_test = 'eval_dict.txt'
params.output = 'pidg_vect.txt'
params.matrix = 'matrix.txt'

Couldn't find it. Thanks.

**Comment by keleog** [comment]
Hi, the files you requested (cbow15, final_dict and eval_dict) are here - https://drive.google.com/drive/folders/1RW4ssPIZxFeUJ5WBMlT4crH0QAfw91_R?usp=sharing

For glove, you can download from here - http://nlp.stanford.edu/data/glove.6B.zip

The output and matrix are the respective paths where your output vector and alignment matrix will be saved to.

**Comment by keleog** [comment]
Closing this, feel free to reopen if you have any more questions.

**Comment by CyrilShch** [comment]
Thank you so much for your prompt response and the files! 
One question: how did you make this bilingual lexicon dictionary? 
I tried to find the details of this alignment process in the article, but could not do it. Also, I read the original articles from Facebook and how they suggest making alignment with bilingual lexicon dictionary in supervised and unsupervised manners. Do you think that it is feasible to do it in an unsupervised manner with your pipeline?

@keleog
